In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('Data.csv')
df.head()

,Date,Time,Temperature (°C),Humidity (%),Pressure (hPa),Light Intensity (Lux),CO2 (ppm),PM1.0 (µg/m³),PM2.5 (µg/m³),PM10.0 (µg/m³),Uptime,Sensors Online
0,14/3/2026,11:08:31 am,37.57,37.32,1013.46,15.21,796,50.0,72.0,79.0,NaN,NaN
1,14/3/2026,11:08:41 am,37.56,37.32,1013.51,18.43,782,48.0,70.0,78.0,NaN,NaN
2,14/3/2026,11:08:51 am,37.46,37.43,1013.41,17.97,788,47.0,69.0,77.0,NaN,NaN
3,14/3/2026,11:09:01 am,37.44,37.34,1013.48,17.97,786,48.0,72.0,80.0,NaN,NaN
4,14/3/2026,11:09:11 am,37.46,37.43,1013.44,17.97,800,48.0,71.0,79.0,NaN,NaN

In [3]:
df.describe()

,Temperature (°C),Humidity (%),Pressure (hPa),Light Intensity (Lux),PM1.0 (µg/m³),PM2.5 (µg/m³),PM10.0 (µg/m³),Sensors Online
count,2712.000000,2739.000000,2664.000000,2739.000000,2664.000000,2739.000000,2664.000000,1391.000000
mean,39.648706,46.063081,953.660998,124.458321,26.857733,40.104783,46.805556,2.984903
std,25.245947,15.812370,233.748413,358.988619,21.442419,25.549397,26.751420,0.133257
min,-7.990000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,35.680000,38.495000,1009.690000,11.060000,20.000000,30.000000,35.000000,3.000000
50%,36.310000,51.870000,1010.770000,49.310000,24.000000,38.000000,42.000000,3.000000
75%,37.150000,53.625000,1011.960000,83.870000,33.000000,48.000000,60.000000,3.000000
max,125.000000,100.000000,1014.000000,3002.570000,633.000000,647.000000,658.000000,3.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2712 non-null   float64
 3   Humidity (%)           2739 non-null   float64
 4   Pressure (hPa)         2664 non-null   float64
 5   Light Intensity (Lux)  2739 non-null   float64
 6   CO2 (ppm)              2739 non-null   object
 7   PM1.0 (µg/m³)          2664 non-null   float64
 8   PM2.5 (µg/m³)          2739 non-null   float64
 9   PM10.0 (µg/m³)         2664 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(8), object(4)
memory usage: 257.5+ KB

In [5]:
df.isnull().sum()

Date                        0
Time                        0
Temperature (°C)           33
Humidity (%)                6
Pressure (hPa)             81
Light Intensity (Lux)       6
CO2 (ppm)                   6
PM1.0 (µg/m³)              81
PM2.5 (µg/m³)               6
PM10.0 (µg/m³)             81
Uptime                   1345
Sensors Online           1354
dtype: int64

In [6]:
df['Humidity (%)'].value_counts()

Humidity (%)
0.00     215
60.20     61
53.61     40
53.52     30
49.49     27
        ...
42.42      1
42.61      1
50.75      1
50.85      1
36.21      1
Name: count, Length: 725, dtype: int64

In [7]:
df['Humidity (%)'].fillna(df['Humidity (%)'].mean(), inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2712 non-null   float64
 3   Humidity (%)           2745 non-null   float64
 4   Pressure (hPa)         2664 non-null   float64
 5   Light Intensity (Lux)  2739 non-null   float64
 6   CO2 (ppm)              2739 non-null   object
 7   PM1.0 (µg/m³)          2664 non-null   float64
 8   PM2.5 (µg/m³)          2739 non-null   float64
 9   PM10.0 (µg/m³)         2664 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(8), object(4)
memory usage: 257.5+ KB

In [9]:
df['Temperature (°C)'].fillna(df['Temperature (°C)'].mean(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2745 non-null   float64
 3   Humidity (%)           2745 non-null   float64
 4   Pressure (hPa)         2664 non-null   float64
 5   Light Intensity (Lux)  2739 non-null   float64
 6   CO2 (ppm)              2739 non-null   object
 7   PM1.0 (µg/m³)          2664 non-null   float64
 8   PM2.5 (µg/m³)          2739 non-null   float64
 9   PM10.0 (µg/m³)         2664 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(8), object(4)
memory usage: 257.5+ KB

In [18]:
df['Pressure (hPa)'].fillna(df['Pressure (hPa)'].mean(), inplace=True)
df['Light Intensity (Lux)'].fillna(df['Light Intensity (Lux)'].mean(), inplace=True)
# df['CO2 (ppm)'].fillna(df['CO2 (ppm)'].mean(), inplace=True)
df['PM1.0 (µg/m³)'].fillna(df['PM1.0 (µg/m³)'].mean(), inplace=True)
df['PM2.5 (µg/m³)'].fillna(df['PM2.5 (µg/m³)'].mean(), inplace=True)
# df['PM10 (µg/m³)'].fillna(df['PM10 (µg/m³)'].mean(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2745 non-null   float64
 3   Humidity (%)           2745 non-null   float64
 4   Pressure (hPa)         2745 non-null   float64
 5   Light Intensity (Lux)  2745 non-null   float64
 6   CO2 (ppm)              2739 non-null   object
 7   PM1.0 (µg/m³)          2745 non-null   float64
 8   PM2.5 (µg/m³)          2745 non-null   float64
 9   PM10.0 (µg/m³)         2664 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(8), object(4)
memory usage: 257.5+ KB

In [26]:

df['CO2 (ppm)'] = pd.to_numeric(df['CO2 (ppm)'], errors='coerce')
df['CO2 (ppm)'].fillna(df['CO2 (ppm)'].mean(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2745 non-null   float64
 3   Humidity (%)           2745 non-null   float64
 4   Pressure (hPa)         2745 non-null   float64
 5   Light Intensity (Lux)  2745 non-null   float64
 6   CO2 (ppm)              2745 non-null   float64
 7   PM1.0 (µg/m³)          2745 non-null   float64
 8   PM2.5 (µg/m³)          2745 non-null   float64
 9   PM10.0 (µg/m³)         2745 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(9), object(3)
memory usage: 257.5+ KB

In [21]:
df['PM10.0 (µg/m³)'].fillna(df['PM10.0 (µg/m³)'].mean(), inplace=True)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2745 entries, 0 to 2744
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   2745 non-null   object
 1   Time                   2745 non-null   object
 2   Temperature (°C)       2745 non-null   float64
 3   Humidity (%)           2745 non-null   float64
 4   Pressure (hPa)         2745 non-null   float64
 5   Light Intensity (Lux)  2745 non-null   float64
 6   CO2 (ppm)              2739 non-null   object
 7   PM1.0 (µg/m³)          2745 non-null   float64
 8   PM2.5 (µg/m³)          2745 non-null   float64
 9   PM10.0 (µg/m³)         2745 non-null   float64
 10  Uptime                 1400 non-null   object
 11  Sensors Online         1391 non-null   float64
dtypes: float64(8), object(4)
memory usage: 257.5+ KB

In [37]:
df['Uptime'].fillna(0, inplace=True)

In [38]:
df['Sensors Online'].fillna(0, inplace=True)

In [39]:
from IPython.display import FileLink

# save preprocessed dataframe to CSV in notebook working dir
df.to_csv('prdtreprocessed_data.csv', index=False)

# if you want a quick download link in Jupyter
FileLink('prdtreprocessed_data.csv')

c:\Users\shaik\OneDrive\Desktop\lohia-farm-weather-hub-05\prdtreprocessed_data.csv